code --install-extension EditorConfig.EditorConfig
code --install-extension WakaTime.vscode-wakatime
code --install-extension alexdima.copy-relative-path
code --install-extension dbaeumer.vscode-eslint
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension ms-python.python
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension octref.vetur
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension teabyii.ayu
code --install-extension eamodio.gitlens
code --install-extension esbenp.prettier-vscode
code --install-extension peterjausovec.vscode-docker
code --install-extension formulahendry.code-runner
code --install-extension bierner.markdown-mermaid
